### ISSUE TITLE
feature: Successive invites give a different message

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/imok#76]
**Overview**

Re-sending the intro SMS gives the same message which requires a 'YES' response. 

**Scope**

Send an updated message to people who are confirmed inside the system

**Acceptance Criteria**

- [ ] A different message shows up if people have registered and the admin presses 'resend invite sms'
- [ ] Successive 'YES' messages don't trigger the message in the admin groupchat

**Comment by WheresAlice** [comment]
Do you want it to not send anything to the member if they are already registered? Or should it send a reminder of the commands to use?

**Comment by kimadactyl** [comment]
Good point. How about:

"You are already registered on %(servername). Send INFO for a list of commands"

We should probably have a command to just message (or even call) an admin too huh at some point.
